[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
site_url = "https://fate-calculator2-0.vercel.app"
additional_redirect_urls = ["https://fate-calculator2-0.vercel.app"]

[auth.email]
enable_signup = true
enable_confirmations = false
secure_password_change = true
max_frequency = "1s"
otp_length = 8

[auth.mfa.totp]
enroll_enabled = true
verify_enabled = true

[auth.rate_limit]
email_sent = 1000
sign_in_sign_ups = 1000
token_verifications = 1000
token_refresh = 2000

[functions.verify-stripe-session]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.admin-users]
verify_jwt = false

[functions.create-stripe-portal-session]
verify_jwt = false
