[api]
enabled = true
port = 54321
schemas = ["public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[functions.verify-stripe-session]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.admin-users]
verify_jwt = false
